/* DatumFI · TICKER BUNDLE — curated reference universe for holdings auto-fill.
   Auto-fills STABLE fields only: name / instrumentType / sector / assetClass / geography / expRatio
   + a user-editable reference price. BETA and DIVIDEND YIELD are intentionally BLANK here — the
   earlier from-memory values were unsourced estimates and were stripped (Lesson 47: no number we
   can't trace). They get re-populated, FLAGGED + DATED, by the monthly on-machine reference
   importer. Live PRICE stays manual (priceSource:'manual'; CF-Worker live proxy parked). */
(function (root) {
  'use strict';
  var T = {
    VTI:{"name":"Vanguard Total Stock Market ETF","sector":"Blend","expRatio":0.03,"assetClass":"US Equity","geography":"US","instrumentType":"ETF"},
    VOO:{"name":"Vanguard S&P 500 ETF","sector":"Blend","expRatio":0.03,"assetClass":"US Equity","geography":"US","instrumentType":"ETF"},
    SPY:{"name":"SPDR S&P 500 ETF","sector":"Blend","expRatio":0.09,"assetClass":"US Equity","geography":"US","instrumentType":"ETF"},
    IVV:{"name":"iShares Core S&P 500 ETF","sector":"Blend","expRatio":0.03,"assetClass":"US Equity","geography":"US","instrumentType":"ETF"},
    SPLG:{"name":"SPDR Portfolio S&P 500 ETF","sector":"Blend","expRatio":0.02,"assetClass":"US Equity","geography":"US","instrumentType":"ETF"},
    QQQ:{"name":"Invesco QQQ Trust","sector":"Technology","expRatio":0.2,"assetClass":"US Equity","geography":"US","instrumentType":"ETF"},
    QQQM:{"name":"Invesco NASDAQ 100 ETF","sector":"Technology","expRatio":0.15,"assetClass":"US Equity","geography":"US","instrumentType":"ETF"},
    DIA:{"name":"SPDR Dow Jones Industrial Avg ETF","sector":"Blend","expRatio":0.16,"assetClass":"US Equity","geography":"US","instrumentType":"ETF"},
    IWM:{"name":"iShares Russell 2000 ETF","sector":"Blend","expRatio":0.19,"assetClass":"US Small Cap","geography":"US","instrumentType":"ETF"},
    IJR:{"name":"iShares Core S&P Small-Cap ETF","sector":"Blend","expRatio":0.06,"assetClass":"US Small Cap","geography":"US","instrumentType":"ETF"},
    IJH:{"name":"iShares Core S&P Mid-Cap ETF","sector":"Blend","expRatio":0.05,"assetClass":"US Mid Cap","geography":"US","instrumentType":"ETF"},
    VO:{"name":"Vanguard Mid-Cap ETF","sector":"Blend","expRatio":0.04,"assetClass":"US Mid Cap","geography":"US","instrumentType":"ETF"},
    VB:{"name":"Vanguard Small-Cap ETF","sector":"Blend","expRatio":0.05,"assetClass":"US Small Cap","geography":"US","instrumentType":"ETF"},
    VUG:{"name":"Vanguard Growth ETF","sector":"Growth","expRatio":0.04,"assetClass":"US Equity","geography":"US","instrumentType":"ETF"},
    VTV:{"name":"Vanguard Value ETF","sector":"Value","expRatio":0.04,"assetClass":"US Equity","geography":"US","instrumentType":"ETF"},
    SCHG:{"name":"Schwab US Large-Cap Growth ETF","sector":"Growth","expRatio":0.04,"assetClass":"US Equity","geography":"US","instrumentType":"ETF"},
    SCHD:{"name":"Schwab US Dividend Equity ETF","sector":"Dividend","expRatio":0.06,"assetClass":"US Equity","geography":"US","instrumentType":"ETF"},
    VYM:{"name":"Vanguard High Dividend Yield ETF","sector":"Dividend","expRatio":0.06,"assetClass":"US Equity","geography":"US","instrumentType":"ETF"},
    VIG:{"name":"Vanguard Dividend Appreciation ETF","sector":"Dividend","expRatio":0.06,"assetClass":"US Equity","geography":"US","instrumentType":"ETF"},
    DGRO:{"name":"iShares Core Dividend Growth ETF","sector":"Dividend","expRatio":0.08,"assetClass":"US Equity","geography":"US","instrumentType":"ETF"},
    MTUM:{"name":"iShares MSCI USA Momentum Factor ETF","sector":"Momentum","expRatio":0.15,"assetClass":"US Equity","geography":"US","instrumentType":"ETF"},
    ARKK:{"name":"ARK Innovation ETF","sector":"Technology","expRatio":0.75,"assetClass":"US Equity","geography":"US","instrumentType":"ETF"},
    XLK:{"name":"Technology Select Sector SPDR","sector":"Technology","expRatio":0.09,"assetClass":"US Equity","geography":"US","instrumentType":"ETF"},
    XLF:{"name":"Financial Select Sector SPDR","sector":"Financials","expRatio":0.09,"assetClass":"US Equity","geography":"US","instrumentType":"ETF"},
    XLE:{"name":"Energy Select Sector SPDR","sector":"Energy","expRatio":0.09,"assetClass":"US Equity","geography":"US","instrumentType":"ETF"},
    XLV:{"name":"Health Care Select Sector SPDR","sector":"Healthcare","expRatio":0.09,"assetClass":"US Equity","geography":"US","instrumentType":"ETF"},
    XLY:{"name":"Consumer Discretionary Select SPDR","sector":"Consumer Cyclical","expRatio":0.09,"assetClass":"US Equity","geography":"US","instrumentType":"ETF"},
    XLP:{"name":"Consumer Staples Select Sector SPDR","sector":"Consumer Defensive","expRatio":0.09,"assetClass":"US Equity","geography":"US","instrumentType":"ETF"},
    XLI:{"name":"Industrial Select Sector SPDR","sector":"Industrials","expRatio":0.09,"assetClass":"US Equity","geography":"US","instrumentType":"ETF"},
    XLU:{"name":"Utilities Select Sector SPDR","sector":"Utilities","expRatio":0.09,"assetClass":"US Equity","geography":"US","instrumentType":"ETF"},
    SMH:{"name":"VanEck Semiconductor ETF","sector":"Technology","expRatio":0.35,"assetClass":"US Equity","geography":"US","instrumentType":"ETF"},
    VEA:{"name":"Vanguard Developed Markets ETF","sector":"Blend","expRatio":0.05,"assetClass":"International Equity","geography":"International","instrumentType":"ETF"},
    VWO:{"name":"Vanguard Emerging Markets ETF","sector":"Blend","expRatio":0.08,"assetClass":"Emerging Equity","geography":"Emerging","instrumentType":"ETF"},
    VXUS:{"name":"Vanguard Total International Stock ETF","sector":"Blend","expRatio":0.08,"assetClass":"International Equity","geography":"International","instrumentType":"ETF"},
    IXUS:{"name":"iShares Core MSCI Total Intl Stock ETF","sector":"Blend","expRatio":0.07,"assetClass":"International Equity","geography":"International","instrumentType":"ETF"},
    EFA:{"name":"iShares MSCI EAFE ETF","sector":"Blend","expRatio":0.32,"assetClass":"International Equity","geography":"International","instrumentType":"ETF"},
    IEMG:{"name":"iShares Core MSCI Emerging Markets ETF","sector":"Blend","expRatio":0.09,"assetClass":"Emerging Equity","geography":"Emerging","instrumentType":"ETF"},
    VGK:{"name":"Vanguard FTSE Europe ETF","sector":"Blend","expRatio":0.09,"assetClass":"International Equity","geography":"International","instrumentType":"ETF"},
    BND:{"name":"Vanguard Total Bond Market ETF","sector":"Fixed Income","expRatio":0.03,"assetClass":"US Bonds","geography":"US","instrumentType":"ETF"},
    AGG:{"name":"iShares Core US Aggregate Bond ETF","sector":"Fixed Income","expRatio":0.03,"assetClass":"US Bonds","geography":"US","instrumentType":"ETF"},
    BNDX:{"name":"Vanguard Total International Bond ETF","sector":"Fixed Income","expRatio":0.07,"assetClass":"Intl Bonds","geography":"International","instrumentType":"ETF"},
    TLT:{"name":"iShares 20+ Year Treasury Bond ETF","sector":"Fixed Income","expRatio":0.15,"assetClass":"US Treasuries","geography":"US","instrumentType":"ETF"},
    IEF:{"name":"iShares 7-10 Year Treasury Bond ETF","sector":"Fixed Income","expRatio":0.15,"assetClass":"US Treasuries","geography":"US","instrumentType":"ETF"},
    SHY:{"name":"iShares 1-3 Year Treasury Bond ETF","sector":"Fixed Income","expRatio":0.15,"assetClass":"US Treasuries","geography":"US","instrumentType":"ETF"},
    SGOV:{"name":"iShares 0-3 Month Treasury Bond ETF","sector":"Cash","expRatio":0.09,"assetClass":"US Treasuries","geography":"US","instrumentType":"ETF"},
    BIL:{"name":"SPDR Bloomberg 1-3 Month T-Bill ETF","sector":"Cash","expRatio":0.14,"assetClass":"US Treasuries","geography":"US","instrumentType":"ETF"},
    MUB:{"name":"iShares National Muni Bond ETF","sector":"Fixed Income","expRatio":0.05,"assetClass":"Municipal Bonds","geography":"US","instrumentType":"ETF"},
    LQD:{"name":"iShares iBoxx Inv Grade Corp Bond ETF","sector":"Fixed Income","expRatio":0.14,"assetClass":"Corporate Bonds","geography":"US","instrumentType":"ETF"},
    VFIAX:{"name":"Vanguard 500 Index Admiral","sector":"Blend","expRatio":0.04,"assetClass":"US Equity","geography":"US","instrumentType":"Mutual Fund"},
    VTSAX:{"name":"Vanguard Total Stock Market Admiral","sector":"Blend","expRatio":0.04,"assetClass":"US Equity","geography":"US","instrumentType":"Mutual Fund"},
    VTIAX:{"name":"Vanguard Total Intl Stock Index Admiral","sector":"Blend","expRatio":0.09,"assetClass":"International Equity","geography":"International","instrumentType":"Mutual Fund"},
    VBTLX:{"name":"Vanguard Total Bond Market Admiral","sector":"Fixed Income","expRatio":0.05,"assetClass":"US Bonds","geography":"US","instrumentType":"Mutual Fund"},
    FXAIX:{"name":"Fidelity 500 Index Fund","sector":"Blend","expRatio":0.015,"assetClass":"US Equity","geography":"US","instrumentType":"Mutual Fund"},
    FSKAX:{"name":"Fidelity Total Market Index Fund","sector":"Blend","expRatio":0.015,"assetClass":"US Equity","geography":"US","instrumentType":"Mutual Fund"},
    FZROX:{"name":"Fidelity ZERO Total Market Index","sector":"Blend","expRatio":0,"assetClass":"US Equity","geography":"US","instrumentType":"Mutual Fund"},
    SWPPX:{"name":"Schwab S&P 500 Index Fund","sector":"Blend","expRatio":0.02,"assetClass":"US Equity","geography":"US","instrumentType":"Mutual Fund"},
    VTTSX:{"name":"Vanguard Target Retirement 2060 Fund","sector":"Target Date","expRatio":0.08,"assetClass":"Allocation","geography":"Global","instrumentType":"Mutual Fund"},
    VFFVX:{"name":"Vanguard Target Retirement 2055 Fund","sector":"Target Date","expRatio":0.08,"assetClass":"Allocation","geography":"Global","instrumentType":"Mutual Fund"},
    VTHRX:{"name":"Vanguard Target Retirement 2030 Fund","sector":"Target Date","expRatio":0.08,"assetClass":"Allocation","geography":"Global","instrumentType":"Mutual Fund"},
    AAPL:{"name":"Apple Inc.","sector":"Technology","expRatio":0,"assetClass":"US Equity","geography":"US","instrumentType":"Stock"},
    MSFT:{"name":"Microsoft Corp.","sector":"Technology","expRatio":0,"assetClass":"US Equity","geography":"US","instrumentType":"Stock"},
    NVDA:{"name":"NVIDIA Corp.","sector":"Technology","expRatio":0,"assetClass":"US Equity","geography":"US","instrumentType":"Stock"},
    AMZN:{"name":"Amazon.com, Inc.","sector":"Consumer Cyclical","expRatio":0,"assetClass":"US Equity","geography":"US","instrumentType":"Stock"},
    GOOGL:{"name":"Alphabet Inc. Class A","sector":"Communication Services","expRatio":0,"assetClass":"US Equity","geography":"US","instrumentType":"Stock"},
    GOOG:{"name":"Alphabet Inc. Class C","sector":"Communication Services","expRatio":0,"assetClass":"US Equity","geography":"US","instrumentType":"Stock"},
    META:{"name":"Meta Platforms, Inc.","sector":"Communication Services","expRatio":0,"assetClass":"US Equity","geography":"US","instrumentType":"Stock"},
    TSLA:{"name":"Tesla, Inc.","sector":"Consumer Cyclical","expRatio":0,"assetClass":"US Equity","geography":"US","instrumentType":"Stock"},
    "BRK.B":{"name":"Berkshire Hathaway Class B","sector":"Financials","expRatio":0,"assetClass":"US Equity","geography":"US","instrumentType":"Stock"},
    AVGO:{"name":"Broadcom Inc.","sector":"Technology","expRatio":0,"assetClass":"US Equity","geography":"US","instrumentType":"Stock"},
    JPM:{"name":"JPMorgan Chase & Co.","sector":"Financials","expRatio":0,"assetClass":"US Equity","geography":"US","instrumentType":"Stock"},
    V:{"name":"Visa Inc.","sector":"Financials","expRatio":0,"assetClass":"US Equity","geography":"US","instrumentType":"Stock"},
    MA:{"name":"Mastercard Inc.","sector":"Financials","expRatio":0,"assetClass":"US Equity","geography":"US","instrumentType":"Stock"},
    JNJ:{"name":"Johnson & Johnson","sector":"Healthcare","expRatio":0,"assetClass":"US Equity","geography":"US","instrumentType":"Stock"},
    UNH:{"name":"UnitedHealth Group","sector":"Healthcare","expRatio":0,"assetClass":"US Equity","geography":"US","instrumentType":"Stock"},
    LLY:{"name":"Eli Lilly and Co.","sector":"Healthcare","expRatio":0,"assetClass":"US Equity","geography":"US","instrumentType":"Stock"},
    ABBV:{"name":"AbbVie Inc.","sector":"Healthcare","expRatio":0,"assetClass":"US Equity","geography":"US","instrumentType":"Stock"},
    MRK:{"name":"Merck & Co.","sector":"Healthcare","expRatio":0,"assetClass":"US Equity","geography":"US","instrumentType":"Stock"},
    PFE:{"name":"Pfizer Inc.","sector":"Healthcare","expRatio":0,"assetClass":"US Equity","geography":"US","instrumentType":"Stock"},
    XOM:{"name":"Exxon Mobil Corp.","sector":"Energy","expRatio":0,"assetClass":"US Equity","geography":"US","instrumentType":"Stock"},
    CVX:{"name":"Chevron Corp.","sector":"Energy","expRatio":0,"assetClass":"US Equity","geography":"US","instrumentType":"Stock"},
    PG:{"name":"Procter & Gamble Co.","sector":"Consumer Defensive","expRatio":0,"assetClass":"US Equity","geography":"US","instrumentType":"Stock"},
    KO:{"name":"Coca-Cola Co.","sector":"Consumer Defensive","expRatio":0,"assetClass":"US Equity","geography":"US","instrumentType":"Stock"},
    PEP:{"name":"PepsiCo, Inc.","sector":"Consumer Defensive","expRatio":0,"assetClass":"US Equity","geography":"US","instrumentType":"Stock"},
    COST:{"name":"Costco Wholesale Corp.","sector":"Consumer Defensive","expRatio":0,"assetClass":"US Equity","geography":"US","instrumentType":"Stock"},
    WMT:{"name":"Walmart Inc.","sector":"Consumer Defensive","expRatio":0,"assetClass":"US Equity","geography":"US","instrumentType":"Stock"},
    HD:{"name":"Home Depot, Inc.","sector":"Consumer Cyclical","expRatio":0,"assetClass":"US Equity","geography":"US","instrumentType":"Stock"},
    MCD:{"name":"McDonald's Corp.","sector":"Consumer Cyclical","expRatio":0,"assetClass":"US Equity","geography":"US","instrumentType":"Stock"},
    DIS:{"name":"Walt Disney Co.","sector":"Communication Services","expRatio":0,"assetClass":"US Equity","geography":"US","instrumentType":"Stock"},
    NFLX:{"name":"Netflix, Inc.","sector":"Communication Services","expRatio":0,"assetClass":"US Equity","geography":"US","instrumentType":"Stock"},
    CRM:{"name":"Salesforce, Inc.","sector":"Technology","expRatio":0,"assetClass":"US Equity","geography":"US","instrumentType":"Stock"},
    ADBE:{"name":"Adobe Inc.","sector":"Technology","expRatio":0,"assetClass":"US Equity","geography":"US","instrumentType":"Stock"},
    AMD:{"name":"Advanced Micro Devices","sector":"Technology","expRatio":0,"assetClass":"US Equity","geography":"US","instrumentType":"Stock"},
    INTC:{"name":"Intel Corp.","sector":"Technology","expRatio":0,"assetClass":"US Equity","geography":"US","instrumentType":"Stock"},
    CSCO:{"name":"Cisco Systems, Inc.","sector":"Technology","expRatio":0,"assetClass":"US Equity","geography":"US","instrumentType":"Stock"},
    BAC:{"name":"Bank of America Corp.","sector":"Financials","expRatio":0,"assetClass":"US Equity","geography":"US","instrumentType":"Stock"},
    WFC:{"name":"Wells Fargo & Co.","sector":"Financials","expRatio":0,"assetClass":"US Equity","geography":"US","instrumentType":"Stock"},
    T:{"name":"AT&T Inc.","sector":"Communication Services","expRatio":0,"assetClass":"US Equity","geography":"US","instrumentType":"Stock"},
    VZ:{"name":"Verizon Communications","sector":"Communication Services","expRatio":0,"assetClass":"US Equity","geography":"US","instrumentType":"Stock"},
    BHF:{"name":"Brighthouse Financial","sector":"Financials","expRatio":0,"assetClass":"US Equity","geography":"US","instrumentType":"Stock"},
    BTC:{"name":"Bitcoin","sector":"Digital Asset","expRatio":0,"assetClass":"Cryptocurrency","geography":"Global","instrumentType":"Crypto"},
    ETH:{"name":"Ethereum","sector":"Digital Asset","expRatio":0,"assetClass":"Cryptocurrency","geography":"Global","instrumentType":"Crypto"},
    IBIT:{"name":"iShares Bitcoin Trust","sector":"Digital Asset","expRatio":0.25,"assetClass":"Cryptocurrency","geography":"Global","instrumentType":"ETF"},
    FBTC:{"name":"Fidelity Wise Origin Bitcoin Fund","sector":"Digital Asset","expRatio":0.25,"assetClass":"Cryptocurrency","geography":"Global","instrumentType":"ETF"}
  };
  if (typeof module !== 'undefined' && module.exports) module.exports = T;
  if (root) root.TICKER_BUNDLE = T;
})(typeof self !== 'undefined' ? self : (typeof window !== 'undefined' ? window : this));
