/* DatumFI · TICKER BUNDLE — curated reference universe for holdings auto-fill.
   Auto-fills STABLE fields: name / instrumentType / sector / assetClass / geography / expRatio
   + curated beta / dividendYield for the Daniel-holdings seed (Ticker Bundle Seed, merged 2026-07-07).
   Seed provenance: expRatioSrc/betaSrc/dividendYieldSrc = 'curated' (fund-doc sourced, L47 — traceable,
   never guessed). Seed 0/blank beta|yield stays BLANK (blank ≠ zero). CIT:<slug> plan-only rows carry
   name/class/geo/sector, no price/beta/yield (no market ticker). Raw seed vocab is normalized to the app
   canonical enums (_V_GE/_V_AC/_V_SE/_V_IN); unmapped strings go SILENT (blank), never fabricated.
   Live PRICE stays manual (priceSource:'manual'; CF-Worker live proxy parked). */
(function (root) {
  'use strict';
  var T = {
    AAPL:{"name":"Apple Inc.","instrumentType":"Stock","sector":"Technology","assetClass":"US Equity","geography":"US"},
    ABBV:{"name":"AbbVie Inc.","instrumentType":"Stock","sector":"Healthcare","assetClass":"US Equity","geography":"US"},
    ACWI:{"name":"iShares MSCI ACWI ETF","instrumentType":"ETF","sector":"Broad Market/Blend","assetClass":"International Equity","geography":"Global","expRatio":0.32,"expRatioSrc":"curated","beta":0.92,"betaSrc":"curated","dividendYield":1.42,"dividendYieldSrc":"curated"},
    ADBE:{"name":"Adobe Inc.","instrumentType":"Stock","sector":"Technology","assetClass":"US Equity","geography":"US"},
    AGG:{"name":"iShares Core US Aggregate Bond ETF","instrumentType":"ETF","sector":"Fixed Income","assetClass":"US Bonds","geography":"US"},
    AMD:{"name":"Advanced Micro Devices","instrumentType":"Stock","sector":"Technology","assetClass":"US Equity","geography":"US"},
    AMZN:{"name":"Amazon.com, Inc.","instrumentType":"Stock","sector":"Consumer Cyclical","assetClass":"US Equity","geography":"US"},
    APH:{"name":"Amphenol Corporation","instrumentType":"Stock","sector":"Technology","assetClass":"US Equity","geography":"US","beta":1.24,"betaSrc":"curated","dividendYield":0.6,"dividendYieldSrc":"curated"},
    ARKK:{"name":"ARK Innovation ETF","instrumentType":"ETF","sector":"Technology","assetClass":"US Equity","geography":"US"},
    AVGO:{"name":"Broadcom Inc.","instrumentType":"Stock","sector":"Technology","assetClass":"US Equity","geography":"US"},
    BAC:{"name":"Bank of America Corp.","instrumentType":"Stock","sector":"Financials","assetClass":"US Equity","geography":"US"},
    BHF:{"name":"Brighthouse Financial","instrumentType":"Stock","sector":"Financials","assetClass":"US Equity","geography":"US","beta":0.87,"betaSrc":"curated"},
    BIL:{"name":"SPDR Bloomberg 1-3 Month T-Bill ETF","instrumentType":"ETF","sector":"Cash","assetClass":"US Treasuries","geography":"US"},
    BIV:{"name":"Vanguard Intermediate-Term Bond ETF","instrumentType":"ETF","assetClass":"Bonds","geography":"US","expRatio":0.03,"expRatioSrc":"curated","beta":0.26,"betaSrc":"curated","dividendYield":4.24,"dividendYieldSrc":"curated"},
    BND:{"name":"Vanguard Total Bond Market ETF","instrumentType":"ETF","sector":"Fixed Income","assetClass":"US Bonds","geography":"US","expRatio":0.03,"expRatioSrc":"curated","beta":0.98,"betaSrc":"curated","dividendYield":3.98,"dividendYieldSrc":"curated"},
    BNDX:{"name":"Vanguard Total International Bond ETF","instrumentType":"ETF","sector":"Fixed Income","assetClass":"Intl Bonds","geography":"International"},
    BOTZ:{"name":"Global X Robotics & Artificial Intelligence ETF","instrumentType":"ETF","sector":"Technology","assetClass":"International Equity","geography":"Global","expRatio":0.68,"expRatioSrc":"curated","beta":1.46,"betaSrc":"curated","dividendYield":0.63,"dividendYieldSrc":"curated"},
    "BRK.B":{"name":"Berkshire Hathaway Class B","instrumentType":"Stock","sector":"Financials","assetClass":"US Equity","geography":"US"},
    BTC:{"name":"Bitcoin","instrumentType":"Crypto","sector":"Digital Asset","assetClass":"Cryptocurrency","geography":"Global"},
    "BTC/USD":{"name":"Bitcoin (BTC/USD)","sector":"Crypto","assetClass":"Crypto","geography":"Global"},
    CASH:{"name":"Cash","instrumentType":"CASH (sweep)","assetClass":"Cash"},
    "CIT:MID-CAP-VALUE-TRUST-D":{"name":"Mid-Cap Value Trust D","instrumentType":"Mutual Fund","assetClass":"US Equity","geography":"US"},
    "CIT:SMALL-CAP-CORE-EQUITY-TRUST-D":{"name":"Small-Cap Core Equity Trust D","instrumentType":"Mutual Fund","assetClass":"US Equity","geography":"US"},
    "CIT:SMALL-CAP-VALUE-EQUITY-TRUST-D":{"name":"Small-Cap Value Equity Trust D","instrumentType":"Mutual Fund","assetClass":"US Equity","geography":"US"},
    "CIT:T-ROWE-PRICE-CAPITAL-APPRECIATION-TRUST-A":{"name":"T. Rowe Price Capital Appreciation Trust A","instrumentType":"Mutual Fund","assetClass":"Mixed/Allocation","geography":"US"},
    "CIT:T-ROWE-PRICE-EQUITY-INCOME-TRUST-B":{"name":"T. Rowe Price Equity Income Trust B","instrumentType":"Mutual Fund","assetClass":"US Equity","geography":"US"},
    "CIT:T-ROWE-PRICE-RETIREMENT-2005-TRUST-B":{"name":"T. Rowe Price Retirement 2005 Trust B","instrumentType":"Mutual Fund","assetClass":"Mixed/Allocation"},
    "CIT:T-ROWE-PRICE-RETIREMENT-2010-TRUST-B":{"name":"T. Rowe Price Retirement 2010 Trust B","instrumentType":"Mutual Fund","assetClass":"Mixed/Allocation"},
    "CIT:T-ROWE-PRICE-RETIREMENT-2015-TRUST-B":{"name":"T. Rowe Price Retirement 2015 Trust B","instrumentType":"Mutual Fund","assetClass":"Mixed/Allocation"},
    "CIT:T-ROWE-PRICE-RETIREMENT-2020-TRUST-B":{"name":"T. Rowe Price Retirement 2020 Trust B","instrumentType":"Mutual Fund","assetClass":"Mixed/Allocation"},
    "CIT:T-ROWE-PRICE-RETIREMENT-2025-TRUST-B":{"name":"T. Rowe Price Retirement 2025 Trust B","instrumentType":"Mutual Fund","assetClass":"Mixed/Allocation"},
    "CIT:T-ROWE-PRICE-RETIREMENT-2030-TRUST-B":{"name":"T. Rowe Price Retirement 2030 Trust B","instrumentType":"Mutual Fund","assetClass":"Mixed/Allocation"},
    "CIT:T-ROWE-PRICE-RETIREMENT-2035-TRUST-B":{"name":"T. Rowe Price Retirement 2035 Trust B","instrumentType":"Mutual Fund","assetClass":"Mixed/Allocation"},
    "CIT:T-ROWE-PRICE-RETIREMENT-2040-TRUST-B":{"name":"T. Rowe Price Retirement 2040 Trust B","instrumentType":"Mutual Fund","assetClass":"Mixed/Allocation"},
    "CIT:T-ROWE-PRICE-RETIREMENT-2045-TRUST-B":{"name":"T. Rowe Price Retirement 2045 Trust B","instrumentType":"Mutual Fund","assetClass":"Mixed/Allocation"},
    "CIT:T-ROWE-PRICE-RETIREMENT-2050-TRUST-B":{"name":"T. Rowe Price Retirement 2050 Trust B","instrumentType":"Mutual Fund","assetClass":"Mixed/Allocation"},
    "CIT:T-ROWE-PRICE-RETIREMENT-2055-TRUST-B":{"name":"T. Rowe Price Retirement 2055 Trust B","instrumentType":"Mutual Fund","assetClass":"Mixed/Allocation"},
    "CIT:T-ROWE-PRICE-RETIREMENT-2060-TRUST-B":{"name":"T. Rowe Price Retirement 2060 Trust B","instrumentType":"Mutual Fund","assetClass":"Mixed/Allocation"},
    "CIT:T-ROWE-PRICE-RETIREMENT-2065-TRUST-B":{"name":"T. Rowe Price Retirement 2065 Trust B","instrumentType":"Mutual Fund","assetClass":"Mixed/Allocation"},
    "CIT:T-ROWE-PRICE-RETIREMENT-BALANCED-TRUST-B":{"name":"T. Rowe Price Retirement Balanced Trust B","instrumentType":"Mutual Fund","assetClass":"Mixed/Allocation"},
    "CIT:T-ROWE-PRICE-US-MID-CAP-GROWTH-EQUITY-TRUST-D":{"name":"T. Rowe Price US Mid Cap Growth Equity Trust D","instrumentType":"Mutual Fund","assetClass":"US Equity","geography":"US"},
    CNRG:{"name":"SPDR S&P Kensho Clean Power ETF","instrumentType":"ETF","sector":"Energy","assetClass":"US Equity","geography":"US","expRatio":0.45,"expRatioSrc":"curated","beta":1.42,"betaSrc":"curated","dividendYield":1.16,"dividendYieldSrc":"curated"},
    COST:{"name":"Costco Wholesale Corp.","instrumentType":"Stock","sector":"Consumer Defensive","assetClass":"US Equity","geography":"US"},
    CRM:{"name":"Salesforce, Inc.","instrumentType":"Stock","sector":"Technology","assetClass":"US Equity","geography":"US"},
    CSCO:{"name":"Cisco Systems, Inc.","instrumentType":"Stock","sector":"Technology","assetClass":"US Equity","geography":"US"},
    CSDIX:{"name":"Cohen & Steers Institutional Realty Shares","instrumentType":"Mutual Fund","sector":"Real Estate/REIT","assetClass":"International Equity","geography":"International","expRatio":0.85,"expRatioSrc":"curated"},
    CVX:{"name":"Chevron Corp.","instrumentType":"Stock","sector":"Energy","assetClass":"US Equity","geography":"US"},
    DGRO:{"name":"iShares Core Dividend Growth ETF","instrumentType":"ETF","sector":"Dividend","assetClass":"US Equity","geography":"US","expRatio":0.08,"expRatioSrc":"curated","beta":0.86,"betaSrc":"curated","dividendYield":1.92,"dividendYieldSrc":"curated"},
    DIA:{"name":"SPDR Dow Jones Industrial Avg ETF","instrumentType":"ETF","sector":"Blend","assetClass":"US Equity","geography":"US"},
    DIS:{"name":"Walt Disney Co.","instrumentType":"Stock","sector":"Communication Services","assetClass":"US Equity","geography":"US"},
    DODIX:{"name":"Dodge & Cox Income Fund","instrumentType":"Mutual Fund","assetClass":"Bonds","expRatio":0.41,"expRatioSrc":"curated"},
    EFA:{"name":"iShares MSCI EAFE ETF","instrumentType":"ETF","sector":"Blend","assetClass":"International Equity","geography":"International"},
    ETH:{"name":"Ethereum","instrumentType":"Crypto","sector":"Digital Asset","assetClass":"Cryptocurrency","geography":"Global"},
    "ETH/USD":{"name":"Ethereum (ETH/USD)","sector":"Crypto","assetClass":"Crypto","geography":"Global"},
    ETHA:{"name":"iShares Ethereum Trust ETF","instrumentType":"ETF","sector":"Crypto","assetClass":"US Equity","geography":"US","expRatio":0.23,"expRatioSrc":"curated","beta":2.6,"betaSrc":"curated"},
    FBCGX:{"name":"Fidelity Series Blue Chip Growth Fund","instrumentType":"Mutual Fund","sector":"Broad Market/Blend","assetClass":"US Equity","geography":"US","expRatio":0.45,"expRatioSrc":"curated"},
    FBTC:{"name":"Fidelity Wise Origin Bitcoin Fund","instrumentType":"ETF","sector":"Digital Asset","assetClass":"Cryptocurrency","geography":"Global"},
    FDFIX:{"name":"Fidelity Flex 500 Index Fund","instrumentType":"Mutual Fund","sector":"Broad Market/Blend","assetClass":"US Equity","geography":"US"},
    FITFX:{"name":"Fidelity Flex International Fund","instrumentType":"Mutual Fund","assetClass":"International Equity","geography":"International"},
    FLAPX:{"name":"Fidelity Flex Mid Cap Index Fund","instrumentType":"Mutual Fund","assetClass":"US Equity","geography":"US"},
    FLCNX:{"name":"Fidelity Contrafund K6","instrumentType":"Mutual Fund","assetClass":"US Equity","geography":"US","expRatio":0.45,"expRatioSrc":"curated"},
    FLGXX:{"name":"Fidelity Government Cash Reserves","instrumentType":"CASH (sweep)","assetClass":"Cash"},
    FLRN:{"name":"SPDR Bloomberg Investment Grade Floating Rate ETF","instrumentType":"ETF","assetClass":"Bonds","geography":"US","expRatio":0.15,"expRatioSrc":"curated","beta":0.02,"betaSrc":"curated","dividendYield":4.45,"dividendYieldSrc":"curated"},
    FLTR:{"name":"VanEck IG Floating Rate ETF","instrumentType":"ETF","assetClass":"Bonds","geography":"US","expRatio":0.14,"expRatioSrc":"curated","beta":0.02,"betaSrc":"curated","dividendYield":4.66,"dividendYieldSrc":"curated"},
    FLXSX:{"name":"Fidelity Flex Small Cap Index Fund","instrumentType":"Mutual Fund","assetClass":"US Equity","geography":"US"},
    FNCMX:{"name":"Fidelity Nasdaq Composite Index Fund","instrumentType":"Mutual Fund","assetClass":"US Equity","geography":"US","expRatio":0.29,"expRatioSrc":"curated"},
    FOSFX:{"name":"Fidelity Overseas Fund","instrumentType":"Mutual Fund","assetClass":"International Equity","geography":"International"},
    FPKFX:{"name":"Fidelity Puritan Fund - Class K6","instrumentType":"Mutual Fund","assetClass":"Mixed/Allocation","geography":"US","expRatio":0.38,"expRatioSrc":"curated"},
    FSKAX:{"name":"Fidelity Total Market Index Fund","instrumentType":"Mutual Fund","sector":"Blend","assetClass":"US Equity","geography":"US"},
    FUENX:{"name":"Fidelity Flex Municipal Income Fund","instrumentType":"Mutual Fund","assetClass":"Bonds"},
    FXAIX:{"name":"Fidelity 500 Index Fund","instrumentType":"Mutual Fund","sector":"Blend","assetClass":"US Equity","geography":"US"},
    FXINX:{"name":"Fidelity International Index Fund","instrumentType":"Mutual Fund","assetClass":"International Equity","geography":"International"},
    FXLCX:{"name":"Fidelity Large Cap Stock Index Fund","instrumentType":"Mutual Fund","sector":"Broad Market/Blend","assetClass":"US Equity","geography":"US","beta":1.0,"betaSrc":"curated"},
    FXMCX:{"name":"Fidelity Mid Cap Index Fund","instrumentType":"Mutual Fund","assetClass":"US Equity","geography":"US"},
    FZILX:{"name":"Fidelity ZERO International Index Fund","instrumentType":"Mutual Fund","assetClass":"International Equity","geography":"International"},
    FZROX:{"name":"Fidelity ZERO Total Market Index","instrumentType":"Mutual Fund","sector":"Blend","assetClass":"US Equity","geography":"US"},
    GBIL:{"name":"Goldman Sachs Access Treasury 0-1 Year ETF","instrumentType":"ETF","assetClass":"US Equity","geography":"US","expRatio":0.12,"expRatioSrc":"curated","beta":0.01,"betaSrc":"curated","dividendYield":3.71,"dividendYieldSrc":"curated"},
    GLD:{"name":"SPDR Gold Shares","instrumentType":"ETF","sector":"Gold","assetClass":"International Equity","geography":"Global","expRatio":0.4,"expRatioSrc":"curated","beta":0.828,"betaSrc":"curated"},
    GLDM:{"name":"SPDR Gold MiniShares Trust","instrumentType":"ETF","sector":"Gold","assetClass":"International Equity","geography":"Global","expRatio":0.1,"expRatioSrc":"curated","beta":0.18,"betaSrc":"curated"},
    GLTR:{"name":"abrdn Physical Precious Metals Basket Shares ETF","instrumentType":"ETF","sector":"Gold","assetClass":"International Equity","geography":"Global","expRatio":0.6,"expRatioSrc":"curated","beta":0.26,"betaSrc":"curated"},
    GOOG:{"name":"Alphabet Inc. Class C","instrumentType":"Stock","sector":"Communication Services","assetClass":"US Equity","geography":"US"},
    GOOGL:{"name":"Alphabet Inc. Class A","instrumentType":"Stock","sector":"Communication Services","assetClass":"US Equity","geography":"US"},
    HD:{"name":"Home Depot, Inc.","instrumentType":"Stock","sector":"Consumer Cyclical","assetClass":"US Equity","geography":"US"},
    HON:{"name":"Honeywell International Inc.","instrumentType":"Stock","sector":"Industrials & Defense","assetClass":"US Equity","geography":"US","beta":0.93,"betaSrc":"curated","dividendYield":3.27,"dividendYieldSrc":"curated"},
    HONA:{"name":"Honeywell International Inc. (Class A)","instrumentType":"Stock","sector":"Technology","assetClass":"US Equity","geography":"US","beta":2.81,"betaSrc":"curated"},
    HYLB:{"name":"Xtrackers USD High Yield Corporate Bond ETF","instrumentType":"ETF","assetClass":"Bonds","geography":"US","expRatio":0.05,"expRatioSrc":"curated","beta":0.4,"betaSrc":"curated","dividendYield":6.5,"dividendYieldSrc":"curated"},
    IBIT:{"name":"iShares Bitcoin Trust","instrumentType":"ETF","sector":"Digital Asset","assetClass":"Cryptocurrency","geography":"Global","expRatio":0.25,"expRatioSrc":"curated"},
    IBM:{"name":"International Business Machines Corporation","instrumentType":"Stock","sector":"Technology","assetClass":"US Equity","geography":"US","beta":0.67,"betaSrc":"curated","dividendYield":2.26,"dividendYieldSrc":"curated"},
    IEF:{"name":"iShares 7-10 Year Treasury Bond ETF","instrumentType":"ETF","sector":"Fixed Income","assetClass":"US Treasuries","geography":"US"},
    IEMG:{"name":"iShares Core MSCI Emerging Markets ETF","instrumentType":"ETF","sector":"Blend","assetClass":"Emerging Equity","geography":"Emerging","expRatio":0.09,"expRatioSrc":"curated","beta":0.73,"betaSrc":"curated","dividendYield":2.19,"dividendYieldSrc":"curated"},
    IGSB:{"name":"iShares 1-5 Year Investment Grade Corporate Bond ETF","instrumentType":"ETF","assetClass":"Bonds","geography":"US","expRatio":0.04,"expRatioSrc":"curated","beta":0.12,"betaSrc":"curated","dividendYield":4.59,"dividendYieldSrc":"curated"},
    IJH:{"name":"iShares Core S&P Mid-Cap ETF","instrumentType":"ETF","sector":"Blend","assetClass":"US Mid Cap","geography":"US"},
    IJR:{"name":"iShares Core S&P Small-Cap ETF","instrumentType":"ETF","sector":"Blend","assetClass":"US Small Cap","geography":"US"},
    INTC:{"name":"Intel Corp.","instrumentType":"Stock","sector":"Technology","assetClass":"US Equity","geography":"US"},
    ITOT:{"name":"iShares Core S&P Total U.S. Stock Market ETF","instrumentType":"ETF","sector":"Broad Market/Blend","assetClass":"US Equity","geography":"US","expRatio":0.03,"expRatioSrc":"curated","beta":1.008,"betaSrc":"curated","dividendYield":1.0,"dividendYieldSrc":"curated"},
    IVV:{"name":"iShares Core S&P 500 ETF","instrumentType":"ETF","sector":"Blend","assetClass":"US Equity","geography":"US","expRatio":0.03,"expRatioSrc":"curated","beta":1.0,"betaSrc":"curated","dividendYield":1.09,"dividendYieldSrc":"curated"},
    IWB:{"name":"iShares Russell 1000 ETF","instrumentType":"ETF","sector":"Broad Market/Blend","assetClass":"US Equity","geography":"US","expRatio":0.15,"expRatioSrc":"curated","beta":1.01,"betaSrc":"curated","dividendYield":0.92,"dividendYieldSrc":"curated"},
    IWM:{"name":"iShares Russell 2000 ETF","instrumentType":"ETF","sector":"Blend","assetClass":"US Small Cap","geography":"US"},
    IWO:{"name":"iShares Russell 2000 Growth ETF","instrumentType":"ETF","assetClass":"US Equity","geography":"US","expRatio":0.24,"expRatioSrc":"curated","beta":1.19,"betaSrc":"curated","dividendYield":0.42,"dividendYieldSrc":"curated"},
    IXUS:{"name":"iShares Core MSCI Total Intl Stock ETF","instrumentType":"ETF","sector":"Blend","assetClass":"International Equity","geography":"International","beta":0.77,"betaSrc":"curated","dividendYield":2.91,"dividendYieldSrc":"curated"},
    JCBUX:{"name":"Baird Aggregate Bond Fund Institutional","instrumentType":"Mutual Fund","assetClass":"Bonds","expRatio":0.31,"expRatioSrc":"curated"},
    JEPI:{"name":"JPMorgan Equity Premium Income ETF","instrumentType":"ETF","sector":"Dividend Growth","assetClass":"US Equity","geography":"US","expRatio":0.35,"expRatioSrc":"curated","beta":0.41,"betaSrc":"curated","dividendYield":8.05,"dividendYieldSrc":"curated"},
    JEPQ:{"name":"JPMorgan Nasdaq Equity Premium Income ETF","instrumentType":"ETF","sector":"Dividend Growth","assetClass":"US Equity","geography":"US","expRatio":0.35,"expRatioSrc":"curated","beta":0.76,"betaSrc":"curated","dividendYield":10.41,"dividendYieldSrc":"curated"},
    JMOM:{"name":"JPMorgan U.S. Momentum Factor ETF","instrumentType":"ETF","assetClass":"US Equity","geography":"US","expRatio":0.12,"expRatioSrc":"curated","beta":1.07,"betaSrc":"curated","dividendYield":0.73,"dividendYieldSrc":"curated"},
    JMVYX:{"name":"JPMorgan Mid Cap Value Fund - Class R6","instrumentType":"Mutual Fund","assetClass":"US Equity","geography":"US","expRatio":0.74,"expRatioSrc":"curated"},
    JNJ:{"name":"Johnson & Johnson","instrumentType":"Stock","sector":"Healthcare","assetClass":"US Equity","geography":"US"},
    JPM:{"name":"JPMorgan Chase & Co.","instrumentType":"Stock","sector":"Financials","assetClass":"US Equity","geography":"US"},
    KO:{"name":"Coca-Cola Co.","instrumentType":"Stock","sector":"Consumer Defensive","assetClass":"US Equity","geography":"US"},
    LLY:{"name":"Eli Lilly and Co.","instrumentType":"Stock","sector":"Healthcare","assetClass":"US Equity","geography":"US"},
    LQD:{"name":"iShares iBoxx Inv Grade Corp Bond ETF","instrumentType":"ETF","sector":"Fixed Income","assetClass":"Corporate Bonds","geography":"US"},
    LUNR:{"name":"Intuitive Machines, Inc.","instrumentType":"Stock","sector":"Industrials & Defense","assetClass":"US Equity","geography":"US","beta":1.78,"betaSrc":"curated"},
    MA:{"name":"Mastercard Inc.","instrumentType":"Stock","sector":"Financials","assetClass":"US Equity","geography":"US"},
    MCD:{"name":"McDonald's Corp.","instrumentType":"Stock","sector":"Consumer Cyclical","assetClass":"US Equity","geography":"US"},
    META:{"name":"Meta Platforms, Inc.","instrumentType":"Stock","sector":"Communication Services","assetClass":"US Equity","geography":"US"},
    MRK:{"name":"Merck & Co.","instrumentType":"Stock","sector":"Healthcare","assetClass":"US Equity","geography":"US"},
    MSFT:{"name":"Microsoft Corp.","instrumentType":"Stock","sector":"Technology","assetClass":"US Equity","geography":"US"},
    MTUM:{"name":"iShares MSCI USA Momentum Factor ETF","instrumentType":"ETF","sector":"Momentum","assetClass":"US Equity","geography":"US","expRatio":0.15,"expRatioSrc":"curated","beta":1.07,"betaSrc":"curated","dividendYield":0.58,"dividendYieldSrc":"curated"},
    MUB:{"name":"iShares National Muni Bond ETF","instrumentType":"ETF","sector":"Fixed Income","assetClass":"Municipal Bonds","geography":"US","expRatio":0.05,"expRatioSrc":"curated","beta":0.905,"betaSrc":"curated","dividendYield":3.16,"dividendYieldSrc":"curated"},
    NFLX:{"name":"Netflix, Inc.","instrumentType":"Stock","sector":"Communication Services","assetClass":"US Equity","geography":"US"},
    NOVMX:{"name":"Nomura Small Cap Value Fund - Class R6","instrumentType":"Mutual Fund","assetClass":"US Equity","geography":"US","expRatio":0.9,"expRatioSrc":"curated"},
    NRSFIXED:{"name":"Nationwide Fixed Account (NRS Fixed)","instrumentType":"CASH (sweep)","assetClass":"Bonds"},
    NVDA:{"name":"NVIDIA Corp.","instrumentType":"Stock","sector":"Technology","assetClass":"US Equity","geography":"US"},
    PDGIX:{"name":"T. Rowe Price Dividend Growth Fund - I Class","instrumentType":"Mutual Fund","sector":"Broad Market/Blend","assetClass":"US Equity","geography":"US","expRatio":0.5,"expRatioSrc":"curated"},
    PEP:{"name":"PepsiCo, Inc.","instrumentType":"Stock","sector":"Consumer Defensive","assetClass":"US Equity","geography":"US"},
    PFE:{"name":"Pfizer Inc.","instrumentType":"Stock","sector":"Healthcare","assetClass":"US Equity","geography":"US"},
    PG:{"name":"Procter & Gamble Co.","instrumentType":"Stock","sector":"Consumer Defensive","assetClass":"US Equity","geography":"US"},
    PRHSX:{"name":"T. Rowe Price Health Sciences Fund - I Class","instrumentType":"Mutual Fund","assetClass":"US Equity","geography":"US","expRatio":0.69,"expRatioSrc":"curated"},
    PRMTX:{"name":"T. Rowe Price Communications & Technology Fund - I Class","instrumentType":"Mutual Fund","sector":"Technology","assetClass":"US Equity","geography":"US","expRatio":0.68,"expRatioSrc":"curated"},
    PRSCX:{"name":"T. Rowe Price Science & Technology Fund - Class I","instrumentType":"Mutual Fund","sector":"Technology","assetClass":"US Equity","geography":"US","expRatio":0.67,"expRatioSrc":"curated"},
    QCLN:{"name":"First Trust NASDAQ Clean Edge Green Energy Index Fund","instrumentType":"ETF","sector":"Energy","assetClass":"US Equity","geography":"US","expRatio":0.59,"expRatioSrc":"curated","beta":1.62,"betaSrc":"curated","dividendYield":0.17,"dividendYieldSrc":"curated"},
    QQQ:{"name":"Invesco QQQ Trust","instrumentType":"ETF","sector":"Technology","assetClass":"US Equity","geography":"US"},
    QQQM:{"name":"Invesco NASDAQ 100 ETF","instrumentType":"ETF","sector":"Technology","assetClass":"US Equity","geography":"US"},
    REGGX:{"name":"American Funds Emerging Markets Bond Fund - Class R-6","instrumentType":"Mutual Fund","assetClass":"Bonds","geography":"International","expRatio":0.53,"expRatioSrc":"curated"},
    RFDTX:{"name":"American Funds 2025 Trgt Date Retire R6","instrumentType":"Mutual Fund","assetClass":"US Equity"},
    RFETX:{"name":"American Funds 2030 Trgt Date Retire R6","instrumentType":"Mutual Fund","assetClass":"US Equity"},
    RFFTX:{"name":"American Funds 2035 Trgt Date Retire R6","instrumentType":"Mutual Fund","assetClass":"US Equity"},
    RFGTX:{"name":"American Funds 2040 Trgt Date Retire R6","instrumentType":"Mutual Fund","assetClass":"US Equity"},
    RFHTX:{"name":"American Funds 2045 Trgt Date Retire R6","instrumentType":"Mutual Fund","assetClass":"US Equity","expRatio":0.37,"expRatioSrc":"curated"},
    RFJTX:{"name":"American Funds 2015 Trgt Date Retire R6","instrumentType":"Mutual Fund","assetClass":"US Equity"},
    RFKTX:{"name":"American Funds 2050 Trgt Date Retire R6","instrumentType":"Mutual Fund","assetClass":"US Equity"},
    RFTTX:{"name":"American Funds 2010 Trgt Date Retire R6","instrumentType":"Mutual Fund","assetClass":"US Equity"},
    RFUTX:{"name":"American Funds 2055 Trgt Date Retire R6","instrumentType":"Mutual Fund","assetClass":"US Equity"},
    RFVTX:{"name":"American Funds 2060 Trgt Date Retire R6","instrumentType":"Mutual Fund","assetClass":"US Equity"},
    RNWGX:{"name":"New World Fund - Class R6","instrumentType":"Mutual Fund","assetClass":"International Equity","geography":"International","expRatio":0.57,"expRatioSrc":"curated"},
    ROKT:{"name":"SPDR S&P Kensho Final Frontiers ETF","instrumentType":"ETF","sector":"Industrials & Defense","assetClass":"US Equity","geography":"US","expRatio":0.45,"expRatioSrc":"curated","beta":1.1,"betaSrc":"curated","dividendYield":0.26,"dividendYieldSrc":"curated"},
    RR:{"name":"Richtech Robotics Inc.","instrumentType":"Stock","sector":"Technology","assetClass":"US Equity","geography":"US","beta":2.0,"betaSrc":"curated"},
    RRCTX:{"name":"American Funds 2020 Trgt Date Retire R6","instrumentType":"Mutual Fund","assetClass":"US Equity"},
    SCHA:{"name":"Schwab U.S. Small-Cap ETF","instrumentType":"ETF","assetClass":"US Equity","geography":"US","expRatio":0.03,"expRatioSrc":"curated","beta":1.1,"betaSrc":"curated","dividendYield":1.03,"dividendYieldSrc":"curated"},
    SCHB:{"name":"Schwab U.S. Broad Market ETF","instrumentType":"ETF","sector":"Broad Market/Blend","assetClass":"US Equity","geography":"US","expRatio":0.03,"expRatioSrc":"curated","beta":1.02,"betaSrc":"curated","dividendYield":1.03,"dividendYieldSrc":"curated"},
    SCHD:{"name":"Schwab US Dividend Equity ETF","instrumentType":"ETF","sector":"Dividend","assetClass":"US Equity","geography":"US","expRatio":0.06,"expRatioSrc":"curated","beta":0.91,"betaSrc":"curated","dividendYield":3.26,"dividendYieldSrc":"curated"},
    SCHF:{"name":"Schwab International Equity ETF","instrumentType":"ETF","sector":"Broad Market/Blend","assetClass":"International Equity","geography":"International","expRatio":0.03,"expRatioSrc":"curated","beta":1.065,"betaSrc":"curated","dividendYield":3.06,"dividendYieldSrc":"curated"},
    SCHG:{"name":"Schwab US Large-Cap Growth ETF","instrumentType":"ETF","sector":"Growth","assetClass":"US Equity","geography":"US"},
    SCHH:{"name":"Schwab U.S. REIT ETF","instrumentType":"ETF","sector":"Real Estate/REIT","assetClass":"US Equity","geography":"US","expRatio":0.07,"expRatioSrc":"curated","beta":0.96,"betaSrc":"curated","dividendYield":2.76,"dividendYieldSrc":"curated"},
    SCHO:{"name":"Schwab Short-Term U.S. Treasury ETF","instrumentType":"ETF","assetClass":"US Equity","geography":"US","expRatio":0.03,"expRatioSrc":"curated","beta":0.05,"betaSrc":"curated","dividendYield":3.9,"dividendYieldSrc":"curated"},
    SCHP:{"name":"iShares TIPS Bond ETF","instrumentType":"ETF","assetClass":"Bonds","geography":"US","expRatio":0.03,"expRatioSrc":"curated","beta":0.992,"betaSrc":"curated","dividendYield":4.01,"dividendYieldSrc":"curated"},
    SCHX:{"name":"Schwab U.S. Large-Cap ETF","instrumentType":"ETF","sector":"Broad Market/Blend","assetClass":"US Equity","geography":"US","expRatio":0.03,"expRatioSrc":"curated","beta":1.004,"betaSrc":"curated","dividendYield":1.01,"dividendYieldSrc":"curated"},
    SGOV:{"name":"iShares 0-3 Month Treasury Bond ETF","instrumentType":"ETF","sector":"Cash","assetClass":"US Treasuries","geography":"US"},
    SHV:{"name":"iShares Short Treasury Bond ETF","instrumentType":"ETF","assetClass":"US Equity","geography":"US","expRatio":0.15,"expRatioSrc":"curated","beta":1.103,"betaSrc":"curated","dividendYield":3.82,"dividendYieldSrc":"curated"},
    SHY:{"name":"iShares 1-3 Year Treasury Bond ETF","instrumentType":"ETF","sector":"Fixed Income","assetClass":"US Treasuries","geography":"US","expRatio":0.15,"expRatioSrc":"curated","beta":1.024,"betaSrc":"curated","dividendYield":3.71,"dividendYieldSrc":"curated"},
    SHYG:{"name":"iShares 0-5 Year High Yield Corporate Bond ETF","instrumentType":"ETF","assetClass":"Bonds","geography":"US","expRatio":0.3,"expRatioSrc":"curated","beta":0.28,"betaSrc":"curated","dividendYield":7.01,"dividendYieldSrc":"curated"},
    SJNK:{"name":"SPDR Bloomberg Short Term High Yield Bond ETF","instrumentType":"ETF","assetClass":"Bonds","geography":"US","expRatio":0.4,"expRatioSrc":"curated","beta":0.29,"betaSrc":"curated","dividendYield":7.01,"dividendYieldSrc":"curated"},
    SMH:{"name":"VanEck Semiconductor ETF","instrumentType":"ETF","sector":"Technology","assetClass":"US Equity","geography":"US","expRatio":0.35,"expRatioSrc":"curated","beta":1.557,"betaSrc":"curated","dividendYield":0.19,"dividendYieldSrc":"curated"},
    SNVXX:{"name":"Morgan Stanley Institutional Liquidity Government MMF","instrumentType":"CASH (sweep)","assetClass":"Cash"},
    SOXX:{"name":"iShares Semiconductor ETF","instrumentType":"ETF","sector":"Technology","assetClass":"US Equity","geography":"US","expRatio":0.33,"expRatioSrc":"curated","beta":1.78,"betaSrc":"curated","dividendYield":0.25,"dividendYieldSrc":"curated"},
    SPAXX:{"name":"Fidelity Government Money Market","instrumentType":"CASH (sweep)","assetClass":"Cash"},
    SPCX:{"name":"Space Exploration Technologies Corp (SpaceX)","instrumentType":"Stock","sector":"Industrials & Defense","assetClass":"US Equity","geography":"US"},
    SPLG:{"name":"SPDR Portfolio S&P 500 ETF","instrumentType":"ETF","sector":"Blend","assetClass":"US Equity","geography":"US"},
    SPMD:{"name":"SPDR Portfolio S&P 400 Mid Cap ETF","instrumentType":"ETF","assetClass":"US Equity","geography":"US","expRatio":0.03,"expRatioSrc":"curated","beta":1.02,"betaSrc":"curated","dividendYield":1.21,"dividendYieldSrc":"curated"},
    SPSM:{"name":"SPDR Portfolio S&P 600 Small Cap ETF","instrumentType":"ETF","assetClass":"US Equity","geography":"US","expRatio":0.03,"expRatioSrc":"curated","beta":1.02,"betaSrc":"curated","dividendYield":1.39,"dividendYieldSrc":"curated"},
    SPY:{"name":"SPDR S&P 500 ETF","instrumentType":"ETF","sector":"Blend","assetClass":"US Equity","geography":"US","expRatio":0.095,"expRatioSrc":"curated","beta":0.999,"betaSrc":"curated","dividendYield":1.2,"dividendYieldSrc":"curated"},
    SPYM:{"name":"SPDR Portfolio S&P 500 ETF","instrumentType":"ETF","sector":"Broad Market/Blend","assetClass":"US Equity","geography":"US","expRatio":0.02,"expRatioSrc":"curated","beta":0.999,"betaSrc":"curated","dividendYield":1.04,"dividendYieldSrc":"curated"},
    STIP:{"name":"iShares 0-5 Year TIPS Bond ETF","instrumentType":"ETF","assetClass":"Bonds","geography":"US","expRatio":0.03,"expRatioSrc":"curated","beta":0.12,"betaSrc":"curated","dividendYield":4.92,"dividendYieldSrc":"curated"},
    SWPPX:{"name":"Schwab S&P 500 Index Fund","instrumentType":"Mutual Fund","sector":"Blend","assetClass":"US Equity","geography":"US"},
    T:{"name":"AT&T Inc.","instrumentType":"Stock","sector":"Communication Services","assetClass":"US Equity","geography":"US"},
    TFI:{"name":"SPDR Nuveen Bloomberg Municipal Bond ETF","instrumentType":"ETF","assetClass":"Bonds","geography":"US","expRatio":0.23,"expRatioSrc":"curated","beta":0.3,"betaSrc":"curated","dividendYield":3.47,"dividendYieldSrc":"curated"},
    TLT:{"name":"iShares 20+ Year Treasury Bond ETF","instrumentType":"ETF","sector":"Fixed Income","assetClass":"US Treasuries","geography":"US","expRatio":0.15,"expRatioSrc":"curated","beta":1.107,"betaSrc":"curated","dividendYield":4.56,"dividendYieldSrc":"curated"},
    TROIX:{"name":"T. Rowe Price Overseas Stock Fund - I Class","instrumentType":"Mutual Fund","assetClass":"International Equity","geography":"International","expRatio":0.67,"expRatioSrc":"curated"},
    TSLA:{"name":"Tesla, Inc.","instrumentType":"Stock","sector":"Consumer Cyclical","assetClass":"US Equity","geography":"US","beta":1.8,"betaSrc":"curated"},
    TSPNX:{"name":"T. Rowe Price Spectrum Income Fund I Class","instrumentType":"Mutual Fund","assetClass":"Bonds","expRatio":0.38,"expRatioSrc":"curated"},
    UNH:{"name":"UnitedHealth Group","instrumentType":"Stock","sector":"Healthcare","assetClass":"US Equity","geography":"US"},
    USHY:{"name":"iShares Broad USD High Yield Corporate Bond ETF","instrumentType":"ETF","assetClass":"Bonds","geography":"US","expRatio":0.08,"expRatioSrc":"curated","beta":0.63,"betaSrc":"curated","dividendYield":6.9,"dividendYieldSrc":"curated"},
    V:{"name":"Visa Inc.","instrumentType":"Stock","sector":"Financials","assetClass":"US Equity","geography":"US"},
    VAIPX:{"name":"Vanguard Inflation-Protected Securities Fund Admiral","instrumentType":"Mutual Fund","assetClass":"Bonds","expRatio":0.1,"expRatioSrc":"curated"},
    VB:{"name":"Vanguard Small-Cap ETF","instrumentType":"ETF","sector":"Blend","assetClass":"US Small Cap","geography":"US"},
    VBK:{"name":"Vanguard Small-Cap Growth ETF","instrumentType":"ETF","assetClass":"US Equity","geography":"US","expRatio":0.05,"expRatioSrc":"curated","beta":1.71,"betaSrc":"curated","dividendYield":0.42,"dividendYieldSrc":"curated"},
    VBTLX:{"name":"Vanguard Total Bond Market Admiral","instrumentType":"Mutual Fund","sector":"Fixed Income","assetClass":"US Bonds","geography":"US"},
    VCSH:{"name":"Vanguard Short-Term Corporate Bond ETF","instrumentType":"ETF","assetClass":"Bonds","geography":"US","expRatio":0.03,"expRatioSrc":"curated","beta":0.631,"betaSrc":"curated","dividendYield":4.45,"dividendYieldSrc":"curated"},
    VDE:{"name":"Vanguard Energy ETF","instrumentType":"ETF","sector":"Energy","assetClass":"US Equity","geography":"US","expRatio":0.09,"expRatioSrc":"curated","beta":0.45,"betaSrc":"curated","dividendYield":2.68,"dividendYieldSrc":"curated"},
    VEA:{"name":"Vanguard Developed Markets ETF","instrumentType":"ETF","sector":"Blend","assetClass":"International Equity","geography":"International","expRatio":0.03,"expRatioSrc":"curated","beta":1.024,"betaSrc":"curated","dividendYield":2.56,"dividendYieldSrc":"curated"},
    VEMIX:{"name":"Vanguard Emerging Markets Stock Index Fund Institutional","instrumentType":"Mutual Fund","assetClass":"International Equity","geography":"International","expRatio":0.06,"expRatioSrc":"curated"},
    VEU:{"name":"Vanguard FTSE All-World ex-US ETF","instrumentType":"ETF","sector":"Broad Market/Blend","assetClass":"International Equity","geography":"International","expRatio":0.04,"expRatioSrc":"curated","beta":0.937,"betaSrc":"curated","dividendYield":2.5,"dividendYieldSrc":"curated"},
    VFFVX:{"name":"Vanguard Target Retirement 2055 Fund","instrumentType":"Mutual Fund","sector":"Target Date","assetClass":"Allocation","geography":"Global"},
    VFIAX:{"name":"Vanguard 500 Index Admiral","instrumentType":"Mutual Fund","sector":"Blend","assetClass":"US Equity","geography":"US"},
    VGK:{"name":"Vanguard FTSE Europe ETF","instrumentType":"ETF","sector":"Blend","assetClass":"International Equity","geography":"International"},
    VGLT:{"name":"Vanguard Long-Term Treasury ETF","instrumentType":"ETF","assetClass":"US Equity","geography":"US","expRatio":0.03,"expRatioSrc":"curated","beta":0.999,"betaSrc":"curated","dividendYield":4.61,"dividendYieldSrc":"curated"},
    VGSNX:{"name":"Vanguard Real Estate Index Fund - Institutional Shares","instrumentType":"Mutual Fund","sector":"Real Estate/REIT","assetClass":"US Equity","geography":"US","expRatio":0.11,"expRatioSrc":"curated"},
    VIG:{"name":"Vanguard Dividend Appreciation ETF","instrumentType":"ETF","sector":"Dividend","assetClass":"US Equity","geography":"US","expRatio":0.04,"expRatioSrc":"curated","beta":0.848,"betaSrc":"curated","dividendYield":1.46,"dividendYieldSrc":"curated"},
    VIIIX:{"name":"Vanguard Institutional Index Fund Institutional Plus","instrumentType":"Mutual Fund","sector":"Broad Market/Blend","assetClass":"US Equity","geography":"US","expRatio":0.02,"expRatioSrc":"curated"},
    VINIX:{"name":"Vanguard Institutional Index Fund Institutional","instrumentType":"Mutual Fund","sector":"Broad Market/Blend","assetClass":"US Equity","geography":"US","expRatio":0.035,"expRatioSrc":"curated"},
    VIS:{"name":"Vanguard Industrials ETF","instrumentType":"ETF","sector":"Industrials & Defense","assetClass":"US Equity","geography":"US","expRatio":0.09,"expRatioSrc":"curated","beta":1.04,"betaSrc":"curated","dividendYield":0.87,"dividendYieldSrc":"curated"},
    VIVIX:{"name":"Vanguard Value Index Fund Institutional","instrumentType":"Mutual Fund","assetClass":"US Equity","geography":"US","expRatio":0.03,"expRatioSrc":"curated"},
    VMCIX:{"name":"Vanguard Mid-Cap Index Fund Institutional","instrumentType":"Mutual Fund","assetClass":"US Equity","geography":"US","expRatio":0.03,"expRatioSrc":"curated"},
    VNQ:{"name":"Vanguard Real Estate ETF","instrumentType":"ETF","sector":"Real Estate/REIT","assetClass":"US Equity","geography":"US","expRatio":0.13,"expRatioSrc":"curated","beta":1.008,"betaSrc":"curated","dividendYield":3.57,"dividendYieldSrc":"curated"},
    VO:{"name":"Vanguard Mid-Cap ETF","instrumentType":"ETF","sector":"Blend","assetClass":"US Mid Cap","geography":"US"},
    VOO:{"name":"Vanguard S&P 500 ETF","instrumentType":"ETF","sector":"Blend","assetClass":"US Equity","geography":"US"},
    VPU:{"name":"Vanguard Utilities ETF","instrumentType":"ETF","sector":"Utilities","assetClass":"US Equity","geography":"US","expRatio":0.09,"expRatioSrc":"curated","beta":0.61,"betaSrc":"curated","dividendYield":2.64,"dividendYieldSrc":"curated"},
    VSCIX:{"name":"Vanguard Small-Cap Index Fund Institutional","instrumentType":"Mutual Fund","assetClass":"US Equity","geography":"US","expRatio":0.03,"expRatioSrc":"curated"},
    VSEQX:{"name":"JPMorgan Small Cap Equity Fund - Class R6","instrumentType":"Mutual Fund","assetClass":"US Equity","geography":"US","expRatio":0.74,"expRatioSrc":"curated"},
    VSPMX:{"name":"Vanguard Strategic Equity Fund","instrumentType":"Mutual Fund","assetClass":"US Equity","geography":"US","expRatio":0.03,"expRatioSrc":"curated"},
    VT:{"name":"Vanguard Total World Stock ETF","instrumentType":"ETF","sector":"Broad Market/Blend","assetClass":"International Equity","geography":"Global","expRatio":0.06,"expRatioSrc":"curated","beta":0.978,"betaSrc":"curated","dividendYield":1.59,"dividendYieldSrc":"curated"},
    VTEB:{"name":"Vanguard Tax-Exempt Bond ETF","instrumentType":"ETF","assetClass":"Bonds","geography":"US","expRatio":0.03,"expRatioSrc":"curated","beta":0.25,"betaSrc":"curated","dividendYield":3.34,"dividendYieldSrc":"curated"},
    VTHRX:{"name":"Vanguard Target Retirement 2030 Fund","instrumentType":"Mutual Fund","sector":"Target Date","assetClass":"Allocation","geography":"Global"},
    VTI:{"name":"Vanguard Total Stock Market ETF","instrumentType":"ETF","sector":"Blend","assetClass":"US Equity","geography":"US","expRatio":0.03,"expRatioSrc":"curated","beta":1.004,"betaSrc":"curated","dividendYield":1.05,"dividendYieldSrc":"curated"},
    VTIAX:{"name":"Vanguard Total Intl Stock Index Admiral","instrumentType":"Mutual Fund","sector":"Blend","assetClass":"International Equity","geography":"International","expRatio":0.09,"expRatioSrc":"curated"},
    VTIP:{"name":"Vanguard Short-Term Inflation-Protected Securities ETF","instrumentType":"ETF","assetClass":"Bonds","geography":"US","expRatio":0.03,"expRatioSrc":"curated","beta":0.09,"betaSrc":"curated","dividendYield":4.15,"dividendYieldSrc":"curated"},
    VTSAX:{"name":"Vanguard Total Stock Market Admiral","instrumentType":"Mutual Fund","sector":"Blend","assetClass":"US Equity","geography":"US","expRatio":0.04,"expRatioSrc":"curated"},
    VTSNX:{"name":"Vanguard Total International Stock Index Fund Institutional","instrumentType":"Mutual Fund","assetClass":"International Equity","geography":"International","expRatio":0.06,"expRatioSrc":"curated"},
    VTTSX:{"name":"Vanguard Target Retirement 2060 Fund","instrumentType":"Mutual Fund","sector":"Target Date","assetClass":"Allocation","geography":"Global"},
    VTV:{"name":"Vanguard Value ETF","instrumentType":"ETF","sector":"Value","assetClass":"US Equity","geography":"US"},
    VUG:{"name":"Vanguard Growth ETF","instrumentType":"ETF","sector":"Growth","assetClass":"US Equity","geography":"US"},
    VWO:{"name":"Vanguard Emerging Markets ETF","instrumentType":"ETF","sector":"Blend","assetClass":"Emerging Equity","geography":"Emerging","expRatio":0.06,"expRatioSrc":"curated","beta":0.657,"betaSrc":"curated","dividendYield":2.34,"dividendYieldSrc":"curated"},
    VXUS:{"name":"Vanguard Total International Stock ETF","instrumentType":"ETF","sector":"Blend","assetClass":"International Equity","geography":"International","expRatio":0.05,"expRatioSrc":"curated","beta":0.941,"betaSrc":"curated","dividendYield":2.58,"dividendYieldSrc":"curated"},
    VYM:{"name":"Vanguard High Dividend Yield ETF","instrumentType":"ETF","sector":"Dividend","assetClass":"US Equity","geography":"US"},
    VZ:{"name":"Verizon Communications","instrumentType":"Stock","sector":"Communication Services","assetClass":"US Equity","geography":"US"},
    WFC:{"name":"Wells Fargo & Co.","instrumentType":"Stock","sector":"Financials","assetClass":"US Equity","geography":"US"},
    WFCASH:{"name":"Wealthfront Cash Account (HYSA)","instrumentType":"CASH (sweep)","assetClass":"Cash","dividendYield":77237.0,"dividendYieldSrc":"curated"},
    WIAEX:{"name":"Wasatch Small Cap Growth Fund - Institutional Class","instrumentType":"Mutual Fund","assetClass":"US Equity","geography":"US","expRatio":1.06,"expRatioSrc":"curated"},
    WLTH:{"name":"Wealthfront Corporation","instrumentType":"Stock","sector":"Technology","assetClass":"US Equity","geography":"US"},
    WMT:{"name":"Walmart Inc.","instrumentType":"Stock","sector":"Consumer Defensive","assetClass":"US Equity","geography":"US"},
    XBI:{"name":"SPDR S&P Biotech ETF","instrumentType":"ETF","sector":"Biotech","assetClass":"US Equity","geography":"US","expRatio":0.35,"expRatioSrc":"curated","beta":0.82,"betaSrc":"curated","dividendYield":0.35,"dividendYieldSrc":"curated"},
    XLE:{"name":"Energy Select Sector SPDR","instrumentType":"ETF","sector":"Energy","assetClass":"US Equity","geography":"US","expRatio":0.08,"expRatioSrc":"curated","beta":0.44,"betaSrc":"curated","dividendYield":2.86,"dividendYieldSrc":"curated"},
    XLF:{"name":"Financial Select Sector SPDR","instrumentType":"ETF","sector":"Financials","assetClass":"US Equity","geography":"US"},
    XLI:{"name":"Industrial Select Sector SPDR","instrumentType":"ETF","sector":"Industrials","assetClass":"US Equity","geography":"US","expRatio":0.08,"expRatioSrc":"curated","beta":0.99,"betaSrc":"curated","dividendYield":1.11,"dividendYieldSrc":"curated"},
    XLK:{"name":"Technology Select Sector SPDR","instrumentType":"ETF","sector":"Technology","assetClass":"US Equity","geography":"US"},
    XLP:{"name":"Consumer Staples Select Sector SPDR","instrumentType":"ETF","sector":"Consumer Defensive","assetClass":"US Equity","geography":"US"},
    XLU:{"name":"Utilities Select Sector SPDR","instrumentType":"ETF","sector":"Utilities","assetClass":"US Equity","geography":"US","expRatio":0.08,"expRatioSrc":"curated","beta":0.59,"betaSrc":"curated","dividendYield":2.65,"dividendYieldSrc":"curated"},
    XLV:{"name":"Health Care Select Sector SPDR","instrumentType":"ETF","sector":"Healthcare","assetClass":"US Equity","geography":"US"},
    XLY:{"name":"Consumer Discretionary Select SPDR","instrumentType":"ETF","sector":"Consumer Cyclical","assetClass":"US Equity","geography":"US"},
    XOM:{"name":"Exxon Mobil Corp.","instrumentType":"Stock","sector":"Energy","assetClass":"US Equity","geography":"US"}
  };
  if (typeof module !== 'undefined' && module.exports) module.exports = T;
  if (root) root.TICKER_BUNDLE = T;
})(typeof self !== 'undefined' ? self : (typeof window !== 'undefined' ? window : this));
